### ISSUE TITLE
Solution to stucking on Loading extension module cutils_...

### ISSUE THREAD

**Issue by Bob8259** [Matrix-ASC/DeLA#14]
新年快乐！这不是一个问题，我是想分享一个我遇到的问题给大家。
Thank you for providing the code. I have tried some other code but they directly install pointnet2 from a Github link, which doesn't work. But your code works for me, thank you a lot! 

But I have noticed a minor problem in the code, after installing the prerequisites, the code was stuck on Loading extension module cutils_...
I am using Ubuntu 22.04, cuda 12.

I found the solution, which is to comment out lines 27 and 28 
#sys.stdout = logfile
#sys.stderr = errfile

In this way, the log will not work, but the code will work.

**Comment by binjiechen** [comment]
我刚看到。感谢你的支持。然后下面那个不是bug。Loading extension module cutils_是正常输出，然后的输出被重定向到log文件了，所以看起来像卡住了。实际上按照说明在python train.py后面加个&放到后台再disown就行了。设计上是这样的。
