### ISSUE TITLE
The replication result on the S3DIS dataset cannot reach 74.1%

### ISSUE THREAD

**Issue by warriorsniu** [Matrix-ASC/DeLA#15]
I reproduced the experiment on S3DIS according to the configuration file provided by the repo, but the average miou of the 8 experimental results is 72.11%, and the best log provided by the code repository is only 72.95% of the results (I can't even reproduce a result comparable to this one). Can you provide the log and model with 74.1% miou? Or can you remind me if any content in the configuration file needs to be modified?

**Comment by binjiechen** [comment]
Log and model are under pretrained/.
You need to run the test script to get test performance, which will be 1.0% to 1.5% better than that in log, and will align well with reported performance. I think this is the reason.

**Comment by warriorsniu** [comment]
Thank you! I have successfully reproduced the results！

**Comment by Youyuan287** [comment]
> 日志和模型处于预训练状态。您需要运行测试脚本才能获得测试性能，这将比 log 中的性能好 1.0% 到 1.5%，并且与报告的性能非常一致。我认为这就是原因。

我在ubuntu22.04，4090上重现了实验，但是多个实验结果的平均miou也如上面所说，在val上只有72%左右，test上多次平均也只有73.02%，我既没有达到论文中所描述test的74.1%，也未达到提供的预训练模型test中的73.5%。我没有改动任何原始配置，请问是哪里的配置需要修改吗？还是一些其他的原因？

**Comment by binjiechen** [comment]
> 我在ubuntu22.04，4090上重现了实验，但是多个实验结果的平均miou也如上面所说，在val上只有72%左右，test上多次平均也只有73.02%，我既没有达到论文中所描述test的74.1%，也未达到提供的预训练模型test中的73.5%。我没有改动任何原始配置，请问是哪里的配置需要修改吗？还是一些其他的原因？

你好，首先，预训练模型的结果是74.1%。你可以跑下是不是。如果没问题，其他配置也没动过，那就没什么原因了。跑的时间分散点，或者随机数种子分散点，多跑一些(大概10个)我相信是可以跑出来平均73.5%，最好74%
左右的结果的。有极端好的结果，也会有极端差的结果。跑的少运气原因是很强的。
