### ISSUE TITLE
Found a bug when running the prepare_s3dis. py file

### ISSUE THREAD

**Issue by Youyuan287** [Matrix-ASC/DeLA#17]
**在复现s3dis数据集时，按照readme文档，运行prepare_s3dis.py时，出现以下报错消息：**

    ValueError: could not convert string to float: '103.0\x100000'
    data/Stanford3dDataset_v1.2/Area_5/office_19/Annotations/ceiling_1.txt
很显然，这并不是环境问题，而是在s3dis数据集中Stanford3dDataset_v1.2/Area_5/office_19/Annotations/ceiling_1.txt中出现了文本字符，无法转换为浮点型数据，但是通过报错消息也无法找到具体在哪一行。将以下检测代码嵌入到prepare_s3dis.py中，可具体找出存在文本字符的行号，手动修改即可,检测代码如下：

    def check_file_lines(elem):
        # 初始化一个变量来保存出错的行号
        error_line = None
        # 使用 genfromtxt 读取文件，并捕获转换错误
        try:
            # 这里故意设置 usecols 来处理文件中的单列数据，根据实际需求调整
            points = torch.from_numpy(np.loadtxt(elem, dtype=np.float32))
        except ValueError as e:
            print(f"An error occurred: {e}")
            # 尝试重新读取文件并手动检查每一行
            with open(elem, 'r') as f:
                for i, line in enumerate(f, start=1):
                    try:
                        # 尝试将行内容分割为浮点数列表
                        values = [float(x) for x in line.strip().split()]
                    except ValueError:
                        # 如果转换失败，打印出错的行号和内容
                        print(f"Error converting line {i} to floats: {line.strip()}")
                        break
        if error_line is not None:
            print(f"The error occurred on line {error_line}.")
        else:
            print("No error found while manually checking lines.")

        
嵌入prepare_sedis.py位置如下：

    for elem in sorted(list(pc_path.glob('Annotations/*.txt'))):
          label = elem.stem.split('_')[0]
          try:
              points = torch.from_numpy(np.loadtxt(elem, dtype=np.float32))
          except Exception as e:
              check_file_lines(elem)
              print(elem)
              raise e

**Comment by binjiechen** [comment]
你好，可能是因为我用的是Stanford3dDataset_v1.2_Aligned_Version，你用的是不带Aligned的，然后数据错误的表现方式不同。我其实也不清楚这两个版本有啥区别。
如果有他人遇到这个问题能在这里找到解法挺好的，感谢你的分享。

顺带一提，它显示的报错摘要是'103.0\x100000'，你有没有试过直接搜索字符\x10? 应该也是可以搜到的

**Comment by Youyuan287** [comment]
感谢你的回复，是数据集的问题，项目代码写的很完美。我有尝试过在txt文件中直接搜索，但是很遗憾不能定位错误，可能是需要字符搜索？通过以上所述方法确实可以定位错误，然后手动修改解决。最后再次感谢你

**Comment by binjiechen** [comment]
VSCode里打开正则匹配搜\x10可以搜到吧。
