### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Wanglei794** [Matrix-ASC/DeLA#18]
Thank you for your contribution. I got an error when running the train file, and the error 'type' object is not subscriptable in line 172 of "s3dis.py". But I don't know why.

**Comment by binjiechen** [comment]
Sorry for the late reply.
`def fix_indices(indices: list[torch.Tensor], cnt1: list, cnt2: list):`
In this line, prior to python 3.10, list[torch.Tensor] is not legal grammar. 
This aids vscode's auto completion but has no real effect on the code behavior.
So you can just delete it.
`def fix_indices(indices: list, cnt1: list, cnt2: list):`
This should work fine for python 3.8 or whatever.

**Comment by Wanglei794** [comment]
I have fixed all the bugs and got amazing results on my device, I am currently learning your ideas and code, thank you again for your contribution.

**Comment by Wanglei794** [comment]
不愧是厦大的大佬,hhhh

**Comment by Wanglei794** [comment]
由于我初次了解到您论文中提到的解耦思想，所以没有太深的理解。所以您所提出的局部聚合解耦的精髓在哪里，为什么它占用很小的资源却得到了这么好的结果，烦请您赐教。

**Comment by binjiechen** [comment]
感谢你的认可。关于解耦，以一个点为例，局部聚合主要是
①取邻居特征，这里可以取特征，和相对坐标等，假设这里是K个邻居乘C维特征加3维相对坐标就是 K x C+3
②特征映射/学习，就是MLP，假设是两个全连接 C+3 -> C -> C。这里复杂度是最高的 KC^2
③池化 把 K x C 池化到 C 得到聚合的特征  复杂度是 KC
这个过程中，你可以发现，如果不取相对坐标，那么①和②的顺序是可以交换的，交换后复杂度变为了 KC + C^2
但是不取相对坐标，聚合是有模糊性的，因为此时近邻是唯一的空间信息。
解耦只是证明，把相对坐标提前学，加上一些别的条件，就可以不再取相对坐标，交换①和②。论文理论部分就讲了这件事。
这保证了复杂度低的同时拟合能力是完备的。这是很重要的。
而性能好，是两个因素的结果。
首先，模型要是完备的，不存在不能拟合的东西。不然只是快了是没有用的。
其次，充分的正则化。比方合适的模型尺寸，stochastic depth，预测相对坐标，大的学习率，分割网络中对高层特征的随机丢弃，等等。

希望这能回答你的困惑。

**Comment by Wanglei794** [comment]
感谢您的帮助。我成功在您工作基础上做出了多尺度DeLA，精度平均提升0.3个百分点，这与pointnet的ssg和msg差距类似。请问，如果尝试发论文，我能以您原版的名字命名吗？



---Original---
From: ***@***.***&gt;
Date: Mon, May 20, 2024 20:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Matrix-ASC/DeLA] TypeError (Issue #18)




 
Closed #18 as completed.

**Comment by binjiechen** [comment]
你好，我没有太听懂以原版名字命名的意思。你是指DeLA-xxx吧。这都是可以的，你有命名你研究的权利。
但是，我建议将你的方法再提炼一下，看看能不能也用在别的网络上，然后取一个模型无关的，独属于你研究工作的名字。
整个逻辑类似于目前的模型有什么问题，我们的方法(多尺度特征)如何帮助模型改善性能，等等。
因为一方面DeLA是没有被接收的，另一方面如果一个方法只能用于一个模型结构，适用性较低。这些都不利于你投稿。
