### ISSUE TITLE
请问处理自定义数据集应该如何修改？

### ISSUE THREAD

**Issue by xiaohe3625** [Matrix-ASC/DeLA#2]
您好，感谢您伟大的工作。我目前正在用您的模型进行点云语义分割，我修改了config中的类别数目和prepare_s3ids中类别标签，可以正常预处理点云，但是在训练时出现
![image](https://github.com/Matrix-ASC/DeLA/assets/125250023/b1f0a5de-8131-4d26-bc6d-6496c353cc7a)
我目前无法寻找到错误的地方，请求您的帮助，谢谢！

**Comment by binjiechen** [comment]
你好，导致segmentation fault的原因基本上是c拓展函数出错，这里应该是网格下采样数组越界了。
我猜测你的数据集分辨率与S3DIS不一致，比它粗。我这里是按S3DIS的数据设置的。
首先，你在config里改一下grid_size，这是网格下采样的网格大小设置。依照你自己的数据分布改。经验上，初始网格大小最好是满足网格内基本上是同一类的点。后面依次x2就行。这里如果没问题可以不用改的。
然后，你在s3dis.py第74、76行改一下网格下采样第三个参数。你可以看参数说明改，也可以直接改成1。如果上面的设置没问题，就不会报错了。
其次，记得修改config里的cor_std，这是预测邻居相对坐标时归一化的系数。你可以打开delasemseg第195行注释，同时注释掉194行。跑几个迭代，它会输出每层的方差，你按这个输入就行。记得把代码改回去。
最后，train里面70行的13也记得改成你的类别数。
其他可能也要改的是max_pts，这是每个点云训练时取的最大点数。以及train的46行的loop跟epoch数。loop x epoch等于总epoch数。你可以根据你的数据自行判断。

其他超参如数据增强也请根据实际数据自行修正。

**Comment by xiaohe3625** [comment]
谢谢你，该问题已经解决！

**Comment by Wanglei794** [comment]
哇。我在以您写的框架作为基线，跑自定义数据集总是遇到DataLoader意外退出的问题，当时您的评论是关闭的，现在终于看到解决方案了
