### ISSUE TITLE
您好，我在使用prepare_s3dis.py处理S3DIS数据集的时候遇到了报错

### ISSUE THREAD

**Issue by HJ-Xu** [Matrix-ASC/DeLA#20]
![57bb0c4008217e81ed7520f040de4dd](https://github.com/user-attachments/assets/3bc1e777-4bb1-4a10-a26b-ee78891d471d)
我发现在处理到data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version/Area_5/hallway_6/Annotations/ceiling_1.txt文件时会报错ValueError: the number of columns changed from 6 to 5 at row 180389; use `usecols` to select a subset and avoid this error
但是我打开txt文档并没有发现什么异常情况，请问您遇到过这样的问题么，或者我可以在哪里直接下载您处理好的s3dis数据么

**Comment by HJ-Xu** [comment]
![1727701027667](https://github.com/user-attachments/assets/c9fc5677-7ef0-44de-b07d-322b5d7cfa64)
这是报错位置的数据，看上去并没有什么异常

**Comment by binjiechen** [comment]
你好 这个问题我在prepare_s3dis脚本开头部分已经注释了啊 用vscode查看是可以看到非法字符的 你直接把那行所有看着像空格的删了改成真空格也行的

**Comment by HJ-Xu** [comment]
非常抱歉，我后续浏览了其他人的提问，在其中看到了您的回复，已经修改过了， 感谢您的热心解答
