### ISSUE TITLE
您好，请问您的这篇工作，DeLA，可以归类为CNN-Based吗？

### ISSUE THREAD

**Issue by ruiqi-nju** [Matrix-ASC/DeLA#21]

**Comment by binjiechen** [comment]
你好，我不知道点云处理上有没有标准的卷积，也不知道多数的语境下点云卷积到底指什么，但我个人认为这更多是一个命名相关的问题。
自注意力操作在点云上是良定义的，但卷积不是，我一直觉得很多叫做卷积的方法其实都不是真正意义上的卷积。但我不知道别人怎么理解的。
无论如何，DeLA不是基于卷积的。
