### ISSUE TITLE
s3dis visualization code

### ISSUE THREAD

**Issue by MRCHENWJ** [Matrix-ASC/DeLA#5]
Hello, your work is excellent
Can you provide the s3dis visualization code? thank you!

**Comment by binjiechen** [comment]
Hi, you may refer to [prediction save](https://github.com/Matrix-ASC/DeLA/issues/3#issuecomment-1764212292) and [visualization](https://github.com/Matrix-ASC/DeLA/issues/1#issuecomment-1731558130). The process should be simple and straightforward.
