### ISSUE TITLE
Tensorrt c++ code

### ISSUE THREAD

**Issue by Wansit99** [Matrix-ASC/DeLA#6]
I appreciate your exceptional work. May I inquire if there are plans to release a TensorRT C++ version of the code in the future?

**Comment by binjiechen** [comment]
Hi, thanks for your interest. Given the fact that I'm currently unfamiliar with TensorRT and occupied with other commitments, that version may not appear in the near future.
But I'm always interested in new technologies and I've heard about TensorRT a lot. So it's very likely that I'll work on it when my schedule clears up a bit. No promises though (as I can't predict the future).
