### ISSUE TITLE
Difference between codes and the paper.

### ISSUE THREAD

**Issue by YangParky** [Matrix-ASC/DeLA#7]
Hi, Thanks for your excellent work. The reported number of layers does not appear to be the same as the number of layers in the paper. In your paper, depths are [2 2 2], however, in codes, depths become [4 4 4].
![image](https://github.com/Matrix-ASC/DeLA/assets/38532963/ae6923a3-6c94-4d9f-aa53-50284632f8b5)
![image](https://github.com/Matrix-ASC/DeLA/assets/38532963/a5798622-3996-499c-a0ed-46c1abea33fa)

**Comment by binjiechen** [comment]
Hi, they are actually the same, despite of different appearance.
In the paper, 2 LFPs and 1 MLP is seen as a unit (Fig 1). So depth n equals 2n LFPs and n MLP.
In the code, depth n equals n LFPs and n/2 MLPs. You can check out the Block class (line 68 of delacls.py of ModelNet40).

**Comment by YangParky** [comment]
> Hi, they are actually the same, despite of different appearance. In the paper, 2 LFPs and 1 MLP is seen as a unit (Fig 1). So depth n equals 2n LFPs and n MLP. In the code, depth n equals n LFPs and n/2 MLPs. You can check out the Block class (line 68 of delacls.py of ModelNet40).

Thanks for your patient reply~
