### ISSUE TITLE
请问cpp扩展编译时如下报错怎么解决？

### ISSUE THREAD

**Issue by LLuKaoo** [Matrix-ASC/DeLA#8]
您好，想复现DeLA在S3DIS数据集上的表现出现如下报错，请问您知道如何解决吗？谢谢！
![ee13288469581f4a160d27e4b671bb9](https://github.com/Matrix-ASC/DeLA/assets/116632720/a878e953-303a-4eef-8680-de33d5a928a0)

**Comment by binjiechen** [comment]
你好，我在windows上没跑过深度学习。这个报错看起来是windows/环境相关的。
一个接近但不完全相同的参考是官方文档的[Windows FAQ#Import error](https://pytorch.org/docs/stable/notes/windows.html#import-error)。网上还有许多其他相关问题和讨论。
此外，看你的输出，似乎没有显示编译过程，不知道编译是否成功。如果编译失败，可能是CUDA环境错误。如果编译成功，可能是其他库环境错误。不好说。

**Comment by LLuKaoo** [comment]
好的，谢谢！

**Comment by guoqiw** [comment]
好兄弟可以加个q1374006083吗，我这支楞不起来了

**Comment by LLuKaoo** [comment]
您好，对于这个Decoupled的理解我还有些疑问想请教一下。
Spatial Encode是利用了pointnet的mlp+maxpooling为每个点得到了具有邻域信息的新特征，再利用这个新的特征进行Local Aggregation，我是不是可以理解为前后进行了两次局部聚合呢？如果是这样的话，相较于其他方法，complexity会有所降低嘛？
刚学习点云这块，希望得到您的回答！！

**Comment by binjiechen** [comment]
你好。局部聚合特指点已经有特征了再去聚合(token mixing + channel mixing)。这一步输入一般是邻居点特征跟相对坐标(确保特征指向明确)。简单做法是mlp+池化。可参考SetAbstraction。但这样复杂度高(kqC)。
spatial encoding的做法不是唯一的，目的是取得一个满足条件的特征。有了这个就可以通过简单的带残差连接的逐点mlp(channel mixing)+邻居池化(token mixing)去拟合完整的mlp+池化。复杂度为C^2+kC。具体可见论文3.1-3.2。
局部聚合实际上在网络中进行了很多次。可以看代码实现。并不是说一次spatial encoding加一次邻居池化是局部聚合。spatial encoding只是前提。在DeLA中可以把两个LFP加一个MLP视作一次局部聚合。
你也可以比较下不同方法的训练用时，更直观一点。

**Comment by Youyuan287** [comment]
> 好的，谢谢！

请问您解决了这个问题吗？我想请教一下是如何排错以及解决的，谢谢。

**Comment by Youyuan287** [comment]
> 您好，想复现DeLA在S3DIS数据集上的表现出现如下报错，请问您知道如何解决吗？谢谢！ ![ee13288469581f4a160d27e4b671bb9](https://private-user-images.githubusercontent.com/116632720/278923503-a878e953-303a-4eef-8680-de33d5a928a0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTEwOTUsIm5iZiI6MTcxODk1MDc5NSwicGF0aCI6Ii8xMTY2MzI3MjAvMjc4OTIzNTAzLWE4NzhlOTUzLTMwM2EtNGVlZi04NjgwLWRlMzNkNWE5MjhhMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwNjE5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODJmMDBjNzM2ZjRhYWExODc3ZmNmMTMxMTdiOTUwYWIwODYxYTIxZWQwNGRlMjM5NDAyMDY1YTI2ZGI1NzEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LysPEQdIZbxHKIbfRcyoJqk9H75HWDjhXvacIvHXY2g)

您好，请问您这个问题解决了吗？我现在在windows上运行也遇到了这个问题
